### ISSUE TITLE
error: helm-get-selection: Args out of range: #<buffer *helm-mt*>, 0, 1

### ISSUE THREAD

**Issue by zeltak** [dfdeshom/helm-mt#3]
hi 

i get this error when i launch helm-mt and press start new terminal

helm-get-selection: Args out of range: #<buffer *helm-mt*>, 0, 1

thx

Z

**Comment by dfdeshom** [comment]
I cannot reproduce this using emacs 24.4. and helm 20150423.342 . Could you tell me your package version?

**Comment by dfdeshom** [comment]
I was able to reproduce it and pushed a fix. Thanks!
