### ISSUE TITLE
Option to automatically choose the name of the terminal buffer

### ISSUE THREAD

**Issue by fbob** [dfdeshom/helm-mt#4]
I looove helm-mt, very very handy :)
Thanks !

Could it be possible to add an option to automatically choose/propose the name of the terminal buffer based on the current working directory ?

**Comment by dfdeshom** [comment]
Hi @fbob , yes I think we can pre-populate a buffer name based on the current directory. What would the name of this buffer be? Just the output of `pwd`, ie `/home/user/dir` ?

**Comment by dfdeshom** [comment]
You can now type `C-c n` in the `helm-mt` buffer and it will create a new session based on the name of the current dir. It's available on the master branch now.

**Comment by fbob** [comment]
Greaaat ! 
Many many thanks @dfdeshom , that's super cool and nice from you :+1:
