### ISSUE TITLE
Unable to create a new terminal buffer

### ISSUE THREAD

**Issue by ttmarek** [dfdeshom/helm-mt#9]
**The Problem**
When I run `helm-mt` I cannot create a new terminal buffer. The "Launch a New Terminal" heading doesn't even appear. Everything else works though. If I create terminals outside of `helm-mt` using `M-x term` they _will_ appear in the `helm-mt` list. I can search, and navigate to terminals (created using `M-x term`), I just can't make a _new_ terminal buffer. I have no idea why. I'll type in a name, press enter, and nothing will happen. My `*Messages*` isn't telling me anything, and there also wasn't anything out of ordinary in my `*Compile-log*`.

**When this problem started**
I upgraded from an HDD to an SSD. And as part of that I made a clean install of Ubuntu, Emacs, and all related packages.

**Versions of things**

```
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) 
of 2016-04-17 on lgw01-04, modified by Debian
```

```
  helm            20160730.2304 
  helm-core       20160730.2310
  helm-mt         20151104.2120
  multi-term      20160619.233
```

Any debugging tips would be greatly appreciated.

**Comment by dfdeshom** [comment]
Hi @ttmarek looks like the helm api has changed, specifically around "dummy" sources. I'll try to get a patch soon.

**Comment by dfdeshom** [comment]
@ttmarek I pushed a new version, please try install helm-mt again.

**Comment by fritzgrabo** [comment]
@dfdeshom, I played around with this a little bit earlier today in an attempt to have both helm sources (existing terminals & dummy source for new terminals) use the various helper functions that helm provides.

This seems to work well for me:

``` elisp
(require 'helm-source)

...

(defvar helm-mt/term-source-terminals
  (helm-build-sync-source
      "Terminals"
    :candidates (lambda ()
                  (or
                   (helm-mt/terminal-buffers)
                   (list "")))
    :action (helm-make-actions
             "Switch to terminal buffer"
             (lambda (candidate)
               (switch-to-buffer candidate))
             "Exit marked terminal(s)"
             (lambda (_ignored)
               (helm-mt/delete-marked-terms _ignored)))))

(defvar helm-mt/term-source-terminal-not-found
  (helm-build-dummy-source
      "Launch a new terminal"
    :action (apply 'helm-make-actions
                   (apply 'append
                          (mapcar (lambda (mode)
                                    (list (format "Launch new %s" mode)
                                          `(lambda (candidate)
                                             (helm-mt/launch-term candidate (quote ,mode)))))
                                  helm-mt/all-terminal-modes)))))

(defun helm-mt ()
  "Custom helm buffer for terminals only."
  (interactive)
  (helm :sources '(helm-mt/term-source-terminals
                   helm-mt/term-source-terminal-not-found)
        :keymap helm-mt/keymap
        :buffer "*helm mt*"))
```

**Comment by dfdeshom** [comment]
@fritzgrabo do you want to submit a pull request? I've been meaning to upgrade to the new helm api. The one thing I would change from the above is to use `defun` instead of `defvar`. Makes on-the-fly debugging easier

**Comment by fritzgrabo** [comment]
@dfdeshom sure, I'll give it a shot! Thanks for the feedback.
